# Kokkuvõte {-}

minu bakalaureuseõppe kava *integreeritud loodusteadused* näitab loogiliselt loodusteaduste ja jätkusuutliku arengu akadeemilist suunda avalik-õigusliku ülikooli Tallinna Ülikooli Loodusteaduste ja tervise instituudis esindades ühtlasi terve ja jätkusuutliku eluviisi fookusvaldkonda. Loodusteaduste ja jätkusuutliku arengu akadeemilist suunda juhib Neeme Lumi. Suunas järgitakse bioloogia, füüsika, geoökoloogia, keskkonnakorralduse, biokeemia ja ökoloogia alalist teadustegevust rõhutades ökoloogilisi uuinguid, loodusteaduslikke rakendus- ja alusuuringuid, keskkonnamõju hindamist ning koostööd säästva arengu põhimõtete teema integreerimiseks haridussüsteemi ja ühiskonnakorraldusse. Kuigi vastavalt *Loodus- ja terviseteaduste instituudi arengukavale 2021-2022* lubatakse suurendada jätkusuutliku arengu kursuste arvu keskkonnakorralduse erialas, suletakse keskkonnakorralduse magistriõpe. Vastavalt Tallinna Ülikooli arengukavale on olulisel kohal rahvusvahelistumine ja interdistsiplinaarsus.

Integreeritud loodusteaduste õppekava on märgitud loodusteaduste, matemaatika ja statistika õppevaldkonna keskkonna õppesuuna keskkonnateaduste õppekavade rühma. minu teostatud koormus- ja majanduslikust analüüsist selgus, et integreeritud loodusteaduste õppekava järgi on võimalik täiskoormusel õppida juhul, kui lisaks õppetoetustele on ajaliselt võimalik paigutada süvaõppe kõrvale tulusat teenusepakkumist, mille jaoks on piisav ajaline ruum olemas. Suurim tervislik Euroopa õppepunktide kogus ühe semestri kohta on 32. Integreeritud loodusteaduste õppe põhivaldkonnad on füüsika, keemia, geograafia ja bioloogia, millest tudeng teeb valiku. Täies mahus kõikide pakutavate õppekava kursuste läbimine tähendaks mitmekordset nominaalõppeaega. Loodusteaduste õpet integreerides on püütud eri valdkonnad n-ö ühte patta panna vältides nende kokkusobivust kasutades eri stiile ja süsteeme. Põhivaldkondi toetavad akadeemilise õppe üldkursused, matemaatika ja inglise keel. Lisaks Tallinna Ülikooli diplomile lubatakse õppekava läbijaile Gaia hariduse serti.

Alates õppeaastast 2015/2016 on alati olnud õppest väljalangejaid, keda on üle kahe korra rohkem kui lõpetanuid. Esimene semester on filter, mis näitab, kes jätkab, kes mitte. Põhjuseid jätkamiseks on mitu: edasiõppimine magistratuuris, õpetama, inseneriks või laborandiks asumine. 20% kuni 25% füüsika, bioloogia, geograafia ja keemia õpetajaid on siin maailmas elanud üle $60 \times a$, mis näitab vajadust uute valdkondlike õpetajate järele. Vajadus on ka eri laadi inseneride järele, mistõttu on kehtestatud 2021. a loodus- ja täppisteaduste õppe lõpetanude osakaalu vajadus 30%. Kuigi füüsika ja keemia laboratooriumid on piisavalt varustatud, ei ole tegemist siiski ülikooli vastutusvaldkonnaga.
